steps:
- name: "alpine"
  id: "Replace values in the training config"
  entrypoint: "sh"
  dir: 'gcp'
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < train_config.yaml > train_config.yaml.tmp
      mv train_config.yaml.tmp train_config.yaml
  secretEnv: ['WANDB_API_KEY']

- name: 'alpine'
  id: "Show config"
  waitFor: ['Replace values in the training config']
  entrypoint: "sh"
  dir: 'gcp'
  args:
    - '-c'
    - |
      cat train_config.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI'
  waitFor: ['Replace values in the training config']
  dir: 'gcp'
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west2',
    '--display-name',
    'example-mlops-job',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
    '--command',
    'uv run invoke train data_dir=/gcs/tweets-dataset/data',
  ]
substitutions:
  _VERTEX_TRAIN_CONFIG: 'train_config.yaml'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest
    env: 'WANDB_API_KEY'